# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title :      CryoCloud
author :     CryoCloud Team and Community, Colorado School of Mines
logo :       logo.png

only_build_toc_files: true

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    hackweek: "CryoCloud"
    dates: "October 2022"
    github_org_url: "https://github.com/CryoInTheCloud"
    book_repo: "CryoCloudWebsite"
    website_url: "https://cryointhecloud.com"
    jupyterhub_url: "https://hub.cryointhecloud.com"
    slack_workspace_url: "https://CryoCloud.slack.com"
    docker_image: "https://hub.docker.com/r/cryointhecloud"
    contact_email: "cryocloud@mines.edu"
    dataset: "ICESat-2"
    anon_reporting_url: "https://docs.google.com/forms/d/e/1FAIpQLSck2-lju8SnqefFMaUGT5S5IlmXDC8hkD5O_Pzn8v9DzbdRmQ/viewform"
    project_spreadsheet_url: "https://docs.google.com/spreadsheets/d/1gmTDZhGCuUCIyoXshyJaeIa-aaUkaby8futT7wyB0TQ/edit?usp=sharing"
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image
    - amsmath
    - deflist
    - html_admonition
    - replacements
    - smartquotes
    - tasklist

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
#  execute_notebooks: 'force'
#  execute_notebooks: 'cache'
  execute_notebooks: 'off'
#  exclude_patterns:
#    - "**/dataintegration-1.ipynb"

  allow_errors: false
  # Per-cell notebook execution limit (seconds)
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"
  jupyterhub_url: "https://hub.cryointhecloud.com/"

# Information about where the book exists on the web
repository:
  url: https://github.com/CryoInTheCloud/CryoCloudWebsite # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py:percent

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-LZVEY6377Z
