name: QualityContol

on:
  pull_request:
    branches:
      - main

jobs:
  quality-control:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setupconda

    - name: Install NB-Clean
      run: |
        pip install nb-clean==2.0.2

    - name: Ensure clean notebooks
      run: |
        python .github/workflows/ensure_clean_notebooks.py

    # NOTE: this isn't a comprehensive spellcheck, just common typos, not checking hidden files at the moment
    - name: Spellcheck
      if: always()
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        skip: '*.js,qaqc.yaml,./.git/objects/*'

        ignore_words_list: slippy,trough,thw

    # borrowed from https://github.com/ProjectPythia/pythia-foundations/blob/main/.github/workflows/link-checker.yaml
    - name: Disable Notebook Execution Before Linkcheck
      if: always()
      shell: python
      run: |
        import yaml
        
        with open('./book/_config.yml') as f:
          data = yaml.safe_load(f)
          data['execute']['execute_notebooks'] = 'off'
        
        with open('./book/_config.yml', 'w') as f:
          yaml.dump(data, f)

    - name: Check External Links
      if: always()
      continue-on-error: true
      run: |
        jb build book --builder linkcheck
